### PR TITLE
feat(ui): add toggle for iframe sandbox

### LINKED ISSUE #106: Sandbox isolation options
If you have an iframe, you will get an issue like this:

> Blocked script execution in 'https://thewebsite.com/something/something' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

### Use case: Payment Gateway or isolated environment which requires an iframe.

https://github.com/flawiddsouza/Restfox/blob/d2686837197f8553a9844f8dcf382c5908e7f43a/packages/ui/src/components/IframeFromBuffer.vue#L2

- Proposal add settings to toggle sandbox environment
- Possible values `sandbox="allow-same-origin allow-scripts allow-popups allow-forms"`

### PR DESCRIPTION
**Pull request by eznix86**
fixes #106

### CODE REVIEW

**Comment by flawiddsouza** [comment]
Thanks for the PR. This looks good. Can you change all varialbes that are named disableSandbox to be disableIframeSandbox?
image

**Comment by eznix86** [comment]
fixed

**Comment by flawiddsouza** [comment]
Can you also rename these variables?
image
image
"sandbox" should have the "iframe" prefix before it, as it's related to the iframe.

**Comment by eznix86** [comment]
Fixed

**Comment by flawiddsouza** [comment]
Thank you. One last change:
image
Label should be "Remove Iframe Sandbox Restriction"

**Comment by eznix86** [comment]
Speaking of which maybe this can be improved with sub items. To specifically tick what to enable. What do you think ?

But lets do it later.

**Comment by eznix86** [comment]
Is the desktop version updates automatically after the merge ?

**Comment by eznix86** [comment]
Done! Btw

**Comment by flawiddsouza** [comment]
> Is the desktop version updates automatically after the merge

No, I'll have to push a tag for release. Then it will update.

> Speaking of which maybe this can be improved with sub items. To specifically tick what to enable. What do you think ?

Sub items? Do you mean having separate sections as tabs in the settings dialog?

**Comment by eznix86** [comment]
The sandbox has many items, allows forms, allow downloads etc.


Right now I just added options so a payment gateway work for example.

**Comment by eznix86** [comment]
And is it possible to push a release ? 😅

**Comment by flawiddsouza** [comment]
> The sandbox has many items, allows forms, allow downloads etc.
> 
> Right now I just added options so a payment gateway work for example.

Ah got it. I feel like disabling the iframe sandbox should enable everything. Most people don't like selecting a lot of config for a single thing. We can add more options if people request it.

> And is it possible to push a release ? 😅

Will be doing a release by today end. Thanks for the PR.

**Pull request merged**
