### PR TITLE
feat(ui): folder tab view

### LINKED ISSUE #235: Folder properties as view instead of a popup when clicking on the Folder
Screenshot 2024-09-06 at 10 34 06

What do you think if we show folder properties as a view, I find it's quite a convenient way to have an overview of folder properties.

### PR DESCRIPTION
**Pull request by kobenguyent**
resolves #235 

@flawiddsouza Not sure if we need to remove the Folder Properties on context menu when this PR is approved.

Updated:
- clicking on folder item would open new tab to set auth and header 
- right clicking on properties to open the model to set name and path

Screenshot 2024-09-27 at 12 02 10

### CODE REVIEW

**Comment by flawiddsouza** [comment]
So let's not have the folder view open on clicking the sidebar item. Let it open when clicking folder properties. We can't have both collapse / expanding ui action + opening folder properies in the same ui action. It feels very odd. I want to retain expanding and collapsing folder on click. Let's just open the folder panel instead of folder properties modal when clicking folder properties.

**Comment by flawiddsouza** [comment]
In Postman, there are separate buttons for collapsing / expanding.

How do you collapse / expand in Insomnia if click opens folder panel?

Regardless of their design decisions, I don't want 2 ui actions on a single click. I specifically want to preserve click to collapse / expand. If you want this new behavior, you can make this a setting. Not the default behavior, so you can have the ux you like, while the default ux is preserved.

Bruno actually behaves the same way. Where click expands / collapses, while right click -> Settings opens the folder view.

**Comment by flawiddsouza** [comment]
> they do have folder properties and here is the UI

This seems unnecessary. I don't know why they would keep both Folder Properties and Folder Panel. Seems very odd.

> Expanding / Collapsing when clicking on the folder icon
Clicking folder name will lead to folder panel

I'm open to exploring this ux. Can you see if you can implement this?

**Comment by flawiddsouza** [comment]
Yes. Let's remove auth and headers from folder properties. And remove folder name and parent folder inputs from folder panel.

**Comment by NeuronEnix** [comment]
How does this UX sound?

Single click to expand
Double click to open folder property

**Comment by flawiddsouza** [comment]
> How does this UX sound?
> 
> Single click to expand
> Double click to open postman like folder property/panel
> 
> Or a gear/option icon at the end to open it 
> 
> 

Double click can't be relied on for a primary action. For people who use a touchscreen or a touchpad, it's not a good experience. Only people with a mouse can do this well. Plus the discoverability of this is also very low. As it doesn't seem like standard ui behavior. All primary actions should happen with a singular touch or click.

Adding a gear when there's already a 3 dot context menu opening button beside the folder title is not good as it adds too many clickable actions in a very small area. Also visual clutter. Let's keep this as simple as possible. No exotic custom ui behaviors that are not easy to discover.

In ui ux design we should choose behaviors that are already present in most applications and the user shouldn't feel like they have to learn a new thing to use the application. Every ui action should be obvious.

**Comment by NeuronEnix** [comment]
Low discovery and for touch screen makes sense to not have it.


But would it be ok for the double click feature to be discovered accidentally

**Comment by flawiddsouza** [comment]
@kobenguyent Merging this for now. Let's look into improving the click expand + tab open behavior later as it doesn't seem that pressing.

**Pull request merged**
