### PR TITLE
update: enhance sidebar method ui.

### PR DESCRIPTION
**Pull request by luckytea**
Hello, I took the liberty of improving the sidebar ui since on MacOS it didn't look as good as it could.

after - before example

изображение

### CODE REVIEW

**Comment by flawiddsouza** [comment]
Thanks for the PR.

image
GET and HEAD aren't as bright in saturation as POST, PUT,  PATCH AND OPTIONS. I can see that these are picked from Insomnia.

image
The lighter colors have a hard time in the light mode, so maybe we'll need to increase saturation for those.

One more thing you'll notice, when the title is long, the alignment of method and request name isn't uniform. It would be good if you're able to fix that. This is unrelated to your changes but it would be good to have that change here since we're touching that code.

image
Please add back the spaces that were removed from here.

image
I prefer having an empty line at the end of each file. So please add that back.

**Comment by flawiddsouza** [comment]
Really love the way it looks now. The alignment also looks perfect. Thank you.

GET is the only one that seems off in the dark mode. Feels like it's hurting the eyes.
image
image
Found this shade and it seems to fit well. #ab7aff.

image
There's too much white space between the method name and the request name, so reduce min-width from 0.8rem to 0.6rem.

image
You can remove these styles. They don't seem to be adding anything. In fact, they seem to be misaligning the method name a bit to the bottom.

I think that'll be all the changes from what I can see.

**Comment by flawiddsouza** [comment]
Also please run `npm run lint-fix` once before the commit.

**Comment by luckytea** [comment]
Sure ab7aff looks lovely!

_> min-width from 0.8rem to 0.6rem._
It seems like we were talking about margin-right, update to 0.6rem.

_> align-items: end;_
Perhaps I overthinking here, at first this seemed like a good decision. Removed.

I run `npm run lint-fix` and install editorconfig plugin, but I'm not quite sure that my vscode settings don't overwrite the .editorconfig file. Sorry if i miss something.

**Comment by flawiddsouza** [comment]
Merged. Thanks for the PR.

**Pull request merged**
