### PR TITLE
Allow native wayland options to support HiDPI screens that using fractional scaling (snap builds)

### PR DESCRIPTION
**Pull request by azvyae**
Apparently more people are using larger screen nowadays and they tend to use fractional scaling (especially in wayland). This is what happened when we use electron through xwayland compositor:

image

image

Both images are preserving its size and also the screenshot, but the second picture was taken from the 2.5K monitor and appears to be blurred.

Electron on the other hand already supports native wayland settings so can address this issue by providing simple Execute command:

`/usr/bin/env ELECTRON_OZONE_PLATFORM_HINT=auto restfox`

But because your `electron-build` config (especially snap) doesn't support wayland, so the command line wouldn't work and triggers segmentation error.

image

This PR just simply added `allowNativeWayland` option on snap build so we can activate `ELECTRON_OZONE_PLATFORM_HINT` env.

### CODE REVIEW

**Comment by flawiddsouza** [comment]
Hey @azvyae, thanks for the fix. Can you check if this flag can be moved to the electron builder config here?
image

**Comment by flawiddsouza** [comment]
@azvyae Just to confirm before the merge. Flag works after moving to package.json right?

**Comment by azvyae** [comment]
I can open the snap application now when the flag is there, (mentioning that before I added the configuration, it cannot open the app at all and creating a segmentation fault). But I'm currently struggling to serve the UI, running npm run build-snap inside the electron package folder is indeed creating a snap file, but it showing only white screen because UI is missing, probably because the build setup that I did. Am I missing something?

```bash
(node:60574) electron: Failed to load URL:
file:///snap/restfox/x1/resources/app.asar/ui/index.html with error: ERR_FILE_NOT_FOUND
(Use `restfox --trace-warnings ...` to show where the warning was created)
```

image

**Comment by flawiddsouza** [comment]
To build the ui, use these commands:
```
cd ui
npm run build-desktop-electron
```

Then you will be able to see the ui in the built binary. The above needs to be done before building the binary.

**Comment by azvyae** [comment]
Taken from 2.5K display with 150% fractional scaling on 😁, and seems like there is no blurry problem anymore, to allow the app running on wayland, user should also provide these argument on `.desktop` launcher.

```
/usr/bin/env ELECTRON_OZONE_PLATFORM_HINT=auto restfox
```

You may proceed to merge this PR, thanks.

image

**Comment by flawiddsouza** [comment]
Nice. I was going to say setting that env manually seems cumbersome. But it seems it's working without so that's great.

**Comment by azvyae** [comment]
Actually that env can automatically checks if current display manager is wayland or x11, and will switch to either of two at the runtime, but unfortunately, I don't know where you put the script to generate `.desktop` file in the snap builds.

**Pull request merged**
